"""report_history 테이블 생성 쿼리 추가

Revision ID: 25ca0581bb8b
Revises: d93c35f6e13c
Create Date: 2026-02-19 20:10:10.798969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ca0581bb8b'
down_revision: Union[str, Sequence[str], None] = 'd93c35f6e13c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_history',
    sa.Column('업체명', sa.Text(), nullable=False),
    sa.Column('도로명주소', sa.Text(), nullable=False),
    sa.Column('신고일자', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.PrimaryKeyConstraint('업체명', '도로명주소')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_history')
    # ### end Alembic commands ###
