"""init

Revision ID: d93c35f6e13c
Revises: 
Create Date: 2026-02-19 13:41:55.465064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd93c35f6e13c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo_zscore_hotspots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sigungu_cd', sa.Text(), nullable=False),
    sa.Column('oa_code', sa.BigInteger(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chajoo_dist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sido', sa.Text(), nullable=False),
    sa.Column('sigungu', sa.Text(), nullable=False),
    sa.Column('year', sa.Text(), nullable=False),
    sa.Column('month', sa.Text(), nullable=False),
    sa.Column('SHP_CD', sa.Text(), nullable=True),
    sa.Column('cargo_sales_count', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant_master',
    sa.Column('법정동명', sa.Text(), nullable=True),
    sa.Column('본번', sa.BigInteger(), nullable=True),
    sa.Column('지주', sa.Text(), nullable=True),
    sa.Column('부번', sa.Float(), nullable=True),
    sa.Column('PNU코드', sa.BigInteger(), nullable=True),
    sa.Column('도로명주소', sa.Text(), nullable=False),
    sa.Column('업체명', sa.Text(), nullable=False),
    sa.Column('대표자', sa.Text(), nullable=True),
    sa.Column('min_유휴부지면적', sa.Float(), nullable=True),
    sa.Column('유휴부지면적', sa.Float(), nullable=True),
    sa.Column('신뢰도점수', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('year', sa.Text(), nullable=True),
    sa.Column('month', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('sigungu', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('업체명', '도로명주소')
    )
    op.create_index('idx_restaurant_location', 'restaurant_master', ['latitude', 'longitude'], unique=False)
    op.create_table('restaurant_status',
    sa.Column('업체명', sa.Text(), nullable=False),
    sa.Column('도로명주소', sa.Text(), nullable=False),
    sa.Column('large_vehicle_access', sa.Integer(), nullable=True),
    sa.Column('contract_status', sa.Text(), server_default=sa.text("'후보 식당'"), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('업체명', '도로명주소')
    )
    op.create_table('truckhelper_parking_area',
    sa.Column('공영차고지명', sa.Text(), nullable=False),
    sa.Column('주소', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('공영차고지명', '주소')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('truckhelper_parking_area')
    op.drop_table('restaurant_status')
    op.drop_index('idx_restaurant_location', table_name='restaurant_master')
    op.drop_table('restaurant_master')
    op.drop_table('chajoo_dist')
    op.drop_table('cargo_zscore_hotspots')
    # ### end Alembic commands ###
